// src/helpers/productImageMap.ts
export const productImageMap: { [key: string]: any } = {
  // Products
  kalmatonine: require("../assets/products/kalmatonine.png"),
  ainat_protect: require("../assets/products/ainat_protect.png"),
  maxitone_vitc: require("../assets/products/maxitone_vitc.png"),
  nobios: require("../assets/products/nobios.png"),
  gingerax_sirop: require("../assets/products/gingerax_sirop.png"),
  gingerax_comprimes: require("../assets/products/gingerax_comprimes.png"),
  gingerax_gouttes: require("../assets/products/gingerax_gouttes.png"),
  candidax_ovules: require("../assets/products/candidax_ovules.png"),
  neovizinc: require("../assets/products/neovizinc.png"),
  neuraxone: require("../assets/products/neuraxone.png"),
  tossedyl: require("../assets/products/tossedyl.png"),
  fitorax_cps: require("../assets/products/fitorax_cps.png"),
  fitopolis_cps: require("../assets/products/fitopolis_cps.png"),
  rectolax_lavement: require("../assets/products/rectolax_lavement.png"),
  ircolax: require("../assets/products/ircolax.png"),
  curaler_spray_nasal: require("../assets/products/curaler_spray_nasal.png"),
  nurax_tonus: require("../assets/products/nurax_tonus.png"),
  theramag_375: require("../assets/products/theramag_375.png"),

  // Gadgets (from files/gadgets)
  ainat_protect_Bloc_Carnet: require("../assets/supports/ainat_protect/Bloc_Carnet.png"),
  ainat_protect_Bloc_Chevalet: require("../assets/supports/ainat_protect/Bloc_Chevalet.png"),
  ainat_protect_Boite_gants: require("../assets/supports/ainat_protect/Boite_gants.png"),
  ainat_protect_Gel_Echo: require("../assets/supports/ainat_protect/Gel_Echo.png"),
  ainat_protect_Pyramide: require("../assets/supports/ainat_protect/Pyramide.png"),
  ainat_protect_Stylos: require("../assets/supports/ainat_protect/Stylos.png"),
  kalmatonine_ADV: require("../assets/supports/kalmatonine/ADV.jpg"),
  kalmatonine_Affiche: require("../assets/supports/kalmatonine/Affiche.jpg"),
  kalmatonine_Bloc_Papier: require("../assets/supports/kalmatonine/Bloc_Papier.jpg"),
  kalmatonine_Boite_Mouchoir: require("../assets/supports/kalmatonine/Boite_Mouchoir.jpg"),
  kalmatonine_Fiche_Poso: require("../assets/supports/kalmatonine/Fiche_Poso.jpg"),
  kalmatonine_Presentoir: require("../assets/supports/kalmatonine/Presentoir.jpg"),
  kalmatonine_Reglettes: require("../assets/supports/kalmatonine/Reglettes.jpg"),
  kalmatonine_Pyramide: require("../assets/supports/kalmatonine/Pyramide.jpg"),
  kalmatonine_TAP: require("../assets/supports/kalmatonine/TAP.jpg"),
};

export const pdfMap: { [key: string]: any } = {
  Formation_Marketing_AINAT_Protect: require("../assets/formations/Formation_Marketing_AINAT_Protect.pdf"),
  Formation_Médicale_AINAT_Protect: require("../assets/formations/Formation_Medicale_AINAT_Protect.pdf"),
  Formation_Produit_AINAT_Protect: require("../assets/formations/Formation_Produit_AINAT_Protect.pdf"),
  Formation_Maxitone_VIT_C: require("../assets/formations/Formation Maxitone VIT C.pdf"),
  Argumentaire_Kalmatonine: require("../assets/formations/Argumentaire_kalmatonine.pdf"),
  formation_kalmatonine: require("../assets/formations/formation_kalmatonine.pdf"),
  Argumentaire_Ainat_Protect: require("../assets/formations/Argumentaire_Ainat_Protect.pdf"),
  formation_nobios: require("../assets/formations/Lancement Nobios SB.pdf"),
  Argumentaire_nobios: require("../assets/formations/Argumentaire NOBIOS.pdf"),
  Argumentaire_Nurax_Tonus: require("../assets/formations/ARGUMENTAIRE NURAX TONUS.pdf"),
  Formation_Rectolax_Lavement: require("../assets/formations/Formation RECTOLAX lavement.pdf"),
  Argumentaire_rectolax_lavement: require("../assets/formations/Argumentaire Rectolax Lavement.pdf"),
};
